#from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Nutricionista(models.Model):
    rut_nutricionista = models.IntegerField(primary_key=True)
    nombre_nutricionista = models.CharField(max_length=25)
    apellido_nutricionista = models.CharField(max_length=25)
    correo_nutricionista = models.CharField(max_length=50)
    entidad_nutricionista = models.CharField(max_length=25)
    id_nutricionista = models.CharField(max_length=25)
    contrasena_nutricionista = models.CharField(max_length=8)

class Paciente(models.Model):
    rut_paciente = models.IntegerField(primary_key=True)
    rut_nutricionista = models.ForeignKey(Nutricionista)
    nombre_paciente = models.CharField(max_length=25)
    apellido_paciente = models.CharField(max_length=25)
    edad_paciente = models.IntegerField()
    genero_paciente = models.IntegerField()

class Ficha(models.Model):
    codigo_ficha = models.IntegerField(primary_key=True)
    rut_paciente = models.ForeignKey(Paciente)
    peso_ficha = models.DecimalField(max_digits=6, decimal_places=3)
    talla_ficha = models.DecimalField(max_digits=6, decimal_places=3)
    circunferenciaCintura_ficha = models.DecimalField(max_digits=6, decimal_places=3)
    circunferenciaBraquial = models.DecimalField(max_digits=6, decimal_places=3)
    pliegueSubEscapular = models.DecimalField(max_digits=6, decimal_places=3)
    pliegueTricipital = models.DecimalField(max_digits=6, decimal_places=3)
    pliegueBicipital = models.DecimalField(max_digits=6, decimal_places=3)
    pliegueSupraIliaco = models.DecimalField(max_digits=6, decimal_places=3)
    indiceMasaCorporal_ficha = models.IntegerField()
    riesgoCardioVascular_ficha = models.IntegerField()
    antecedentesPatologicos_ficha = models.TextField()
    signoSintomas_ficha = models.TextField()
    baseFisiologicoFisiopatologico_ficha = models.TextField()

class Clasificacion(models.Model):
    codigo_clasificacion = models.IntegerField()
    nombre_clasificacion = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre_clasificacion

class Alimento(models.Model):
    codigo_alimento = models.IntegerField(primary_key=True)
    codigo_clasificacion = models.ForeignKey(Clasificacion)
    nombre_alimento = models.CharField(max_length=50)
    humedad_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    calorias_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    proteinas_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    hidratosCarbono_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    fibraDietaria_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    lipidos_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    acidoGrasoSaturado_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    acidoGrasoMonoInsaturado_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    acidoGrasoPoliInsaturado_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    colesterol_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    n6_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    n3_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    retinolRe_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    carotenoRe_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    vitATotalRe_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    vitB1_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    vitB2_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    niacina_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    vitB6_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    folatos_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    acidoPantogenico_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    vitC_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    vitE_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    calcio_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    cobre_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    hierro_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    magnesio_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    fosforo_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    potasio_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    selenio_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    sodio_alimento = models.DecimalField(max_digits=6, decimal_places=3)
    zinc_alimento = models.DecimalField(max_digits=6, decimal_places=3)

class Minuta(models.Model):
    codigo_minuta = models.IntegerField(primary_key=True)
    rut_nutricionista = models.ForeignKey(Nutricionista)
    rut_paciente = models.ForeignKey(Paciente)
    codigo_alimento = models.ForeignKey(Alimento)
    servicio = models.CharField(max_length=25)
    cantidad = models.IntegerField()
    proteina = models.DecimalField(max_digits=6, decimal_places=3)
    factorConversion = models.DecimalField(max_digits=6, decimal_places=3)
    nitrogeno = models.DecimalField(max_digits=6, decimal_places=3)
    lisina = models.DecimalField(max_digits=6, decimal_places=3)
    metionina_cistina = models.DecimalField(max_digits=6, decimal_places=3)
    treonina = models.DecimalField(max_digits=6, decimal_places=3)
    triptofano = models.DecimalField(max_digits=6, decimal_places=3)